#!/bin/bash

eleccion_computadora() {
  opciones=("piedra" "papel" "tijera")
  eleccion_computadora=${opciones[$RANDOM % 3]}
  echo $eleccion_computadora
}


determinar_ganador() {
  if [ "$1" == "$2" ]; then
    echo "Empate"
  elif [ "$1" == "piedra" ] && [ "$2" == "tijera" ]; then
    echo "$3"
  elif [ "$1" == "papel" ] && [ "$2" == "piedra" ]; then
    echo "$3"
  elif [ "$1" == "tijera" ] && [ "$2" == "papel" ]; then
    echo "$3"
  else
    echo "la computadora"
  fi
}

jugar() {
  echo "¡Bienvenido al juego de Piedra, Papel o Tijera!"
  echo "Por favor ingresa tu nombre:"
  read nombre_usuario
  echo "---------------------------------------------------------------------------"
  echo "Hola $nombre_usuario, gracias por jugar, lee las instrucciones por favor"

  echo "Por favor elige entre piedra, papel o tijera"
  read eleccion_usuario
  echo "---------------------------------------------------------------------------"
  echo "Tu has elegido $eleccion_usuario"
  eleccion_final=$(echo $eleccion_usuario | tr '[:upper:]' '[:lower:]')

  eleccion_computadora=$(eleccion_computadora)
  echo "La computadora eligió: $eleccion_computadora"

  ganador=$(determinar_ganador "$eleccion_final" "$eleccion_computadora" "$nombre_usuario")
  echo "El ganador es: $ganador"
  echo "Graciar por jugar, puedes consultar la lista de ganadores"
  echo "---------------------------------------------------------------------------"
jugar() {
  echo "¡Bienvenido al juego de Piedra, Papel o Tijera!"
  echo "Por favor ingresa tu nombre:"
  read nombre_usuario
  echo "---------------------------------------------------------------------------"
  echo "Hola $nombre_usuario, gracias por jugar, lee las instrucciones por favor"

  echo "Por favor elige entre piedra, papel o tijera"
  read eleccion_usuario
  echo "---------------------------------------------------------------------------"
  echo "Tu has elegido $eleccion_usuario"
  eleccion_final=$(echo $eleccion_usuario | tr '[:upper:]' '[:lower:]')

  eleccion_computadora=$(eleccion_computadora)
  echo "La computadora eligió: $eleccion_computadora"

  ganador=$(determinar_ganador "$eleccion_final" "$eleccion_computadora" "$nombre_usuario")
  echo "El ganador es: $ganador"
  echo "Graciar por jugar, puedes consultar la lista de ganadores"
  echo "---------------------------------------------------------------------------"
  if [ "$ganador" != "Empate" ]; then
          echo "El ganador de esta partida fue: $ganador en la fecha: $(date)$(hostname -I) " >> .ganadores_respaldo.txt
          base64 .ganadores_respaldo.txt >> ganadores.txt

  fi
}

menu(){
  echo "---------------------------------------------------------------------------"    
  echo "Bienvenido al Menu. Por favor elige una de las opciones"
  echo "1. Jugar a Piedra papel o tijera contra la computadora"
  echo "2. Visualizar la lista de ganadores"
  echo "3. Reinicia la lista de ganadores"
  echo "4. Restaurar la lista de ganadores"
  echo "---------------------------------------------------------------------------"  
  read opcion_usuario
  echo "Ha seleccionado la opcion: $opcion_usuario"
 echo "----------------------------------------------------------------------------" 
  if [ "$opcion_usuario" == "1" ]; then
          jugar
  elif [ "$opcion_usuario" == "2" ]; then
          base64 -d ganadores.txt
  elif [ "$opcion_usuario" == "3" ]; then
          rm -r ganadores.txt
          echo "La lista de ganadores ha sido eliminada"
  elif [ "$opcion_usuario" == "4" ]; then
          cp .ganadores_respaldo.txt ganadores_mid.txt
          base64 ganadores_mid.txt >> ganadores.txt
          rm ganadores_mid.txt
          echo "La lista ha sido restaurada con exito"
  fi

}

menu
